modLoader = "javafml"
loaderVersion = "${forge_loader_range}"
license = "CC BY-NC-ND 4.0"
issueTrackerURL="https://github.com/tristankechlo/RandomMobSizes/issues"

[[mods]]
    modId = "random_mob_sizes"
    version = "${version}"
    displayName = "Random Mob Sizes"
    displayURL="https://github.com/tristankechlo/RandomMobSizes"
    logoFile= "banner.png"
    authors = "Buecher_wurm"
    description = '''configure mobs to spawn in different sizes'''
    displayTest="IGNORE_SERVER_VERSION"

[[dependencies.random_mob_sizes]]
    modId = "forge"
    mandatory = true
    versionRange = "${forge_loader_range}"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.random_mob_sizes]]
    modId = "minecraft"
    mandatory = true
    versionRange = "${version_range}"
    ordering = "NONE"
    side = "BOTH"
