modLoader = "javafml"
loaderVersion = "[44,)"
license = "CC BY-NC-ND 4.0"
issueTrackerURL="https://github.com/tristankechlo/RandomMobSizes/issues"
#showAsResourcePack=false

[[mods]]
modId = "random_mob_sizes"
version = "1.19.3-1.0.1"
displayName = "Random Mob Sizes"
displayURL="https://github.com/tristankechlo/RandomMobSizes"
logoFile="banner.png"
#credits = "Thanks for this example mod goes to Java"
authors = "Buecher_wurm"
description = '''configure mobs to spawn in different sizes'''


[[dependencies.random_mob_sizes]]
    modId = "forge"
    mandatory = true
    versionRange = "[44,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.random_mob_sizes]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19.3,1.20)"
    ordering = "NONE"
    side = "BOTH"
